# TODO: move to pyproject.toml when pixi supports it
# https://github.com/prefix-dev/pixi/issues/79
[project]
name = "dilax"
description = "Differentiable (binned) likelihoods in JAX."
authors = ["Peter Fackeldey <peter.fackeldey@rwth-aachen.de>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64"]
readme = "README.md"
repository = "https://github.com/prefix-dev/pixi"
documentation = "https://dilax.readthedocs.io"

[dependencies]
python = ">3.9,<=3.11"
ipython = "*"
jaxlib = "*"
jax = "*"

[host-dependencies]
pip = "*"

[tasks]
postinstall = "pip install -e '.[dev]' && pip install pre-commit && pre-commit install"
test = "pytest"
lint = "ruff check . --fix --show-fixes"
checkall = "pre-commit run --all-files"
